// Generated by gencpp from file rover_msgs/ArmControl.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_ARMCONTROL_H
#define ROVER_MSGS_MESSAGE_ARMCONTROL_H

#include <ros/service_traits.h>


#include <rover_msgs/ArmControlRequest.h>
#include <rover_msgs/ArmControlResponse.h>


namespace rover_msgs
{

struct ArmControl
{

typedef ArmControlRequest Request;
typedef ArmControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmControl
} // namespace rover_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rover_msgs::ArmControl > {
  static const char* value()
  {
    return "438c11d562dc9fa31889c10ff3e39023";
  }

  static const char* value(const ::rover_msgs::ArmControl&) { return value(); }
};

template<>
struct DataType< ::rover_msgs::ArmControl > {
  static const char* value()
  {
    return "rover_msgs/ArmControl";
  }

  static const char* value(const ::rover_msgs::ArmControl&) { return value(); }
};


// service_traits::MD5Sum< ::rover_msgs::ArmControlRequest> should match
// service_traits::MD5Sum< ::rover_msgs::ArmControl >
template<>
struct MD5Sum< ::rover_msgs::ArmControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rover_msgs::ArmControl >::value();
  }
  static const char* value(const ::rover_msgs::ArmControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rover_msgs::ArmControlRequest> should match
// service_traits::DataType< ::rover_msgs::ArmControl >
template<>
struct DataType< ::rover_msgs::ArmControlRequest>
{
  static const char* value()
  {
    return DataType< ::rover_msgs::ArmControl >::value();
  }
  static const char* value(const ::rover_msgs::ArmControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rover_msgs::ArmControlResponse> should match
// service_traits::MD5Sum< ::rover_msgs::ArmControl >
template<>
struct MD5Sum< ::rover_msgs::ArmControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rover_msgs::ArmControl >::value();
  }
  static const char* value(const ::rover_msgs::ArmControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rover_msgs::ArmControlResponse> should match
// service_traits::DataType< ::rover_msgs::ArmControl >
template<>
struct DataType< ::rover_msgs::ArmControlResponse>
{
  static const char* value()
  {
    return DataType< ::rover_msgs::ArmControl >::value();
  }
  static const char* value(const ::rover_msgs::ArmControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_ARMCONTROL_H
